spring.application.name=demo
#spring.datasource.url=jdbc:postgresql://localhost:5432/psjob
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
debug=true

# --- JWT Configuration ---
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a76dbde1b8b8edce4f7e2a96752345d1
app.jwt.expiration-ms=86400000

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5

# --- OAuth2 Configuration ---
# Remplacez avec votre clientId et clientSecret Google
spring.security.oauth2.client.registration.google.client-id=VOTRE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=VOTRE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
